import random
import string


def generate_random_name() -> str:
    """
    Generate a random string

    Returns
    -------
    str
        string generated by the function
    """
    random.seed()
    lenght = random.randint(5, 20)
    char_set = string.ascii_letters + string.digits
    return "".join([random.choice(string.ascii_letters)] + random.choices(
        char_set, k=lenght))
